from project.controller import Controller

cll = Controller()
print(cll.add_aquarium("FreshwaterAquarium", "Roza"))
print(cll.add_aquarium("FreshwaterAquariumsss", "Roza"))
print(cll.add_aquarium("FreshwaterAquarium", "Zizu"))
print(cll.add_decoration("Ornament"))
print(cll.add_decoration("Plant"))
print(cll.add_decoration("Ornament"))
print(cll.add_decoration("Ornamentssss"))
print(cll.insert_decoration("Roza", "Ornament"))
print(cll.insert_decoration("Roza", "Ornamentssss"))
print(cll.decorations_repository.decorations[0].__class__.__name__)
print(cll.decorations_repository.decorations[1].__class__.__name__)
print(cll.add_fish("Roza","FreshwaterFish", "Ab", "Cd", 1.50))
print(cll.add_fish("Roza","FreshwaterFish", "Ac", "Dc", 2.50))
print(cll.add_fish("Roza","SaltwaterFishhhh", "Ac", "Dc", 2.50))
print(cll.add_fish("Roza","SaltwaterFish", "Ac", "Dc", 2.50))
print(cll.feed_fish("Roza"))
print(cll.calculate_value("Roza"))
print(cll.report())



# print(controller.create_driver("Peter"))
# print(controller.create_car("SportsCar", "Porsche 718 Boxster", 470))
# print(controller.create_car("Sports", "Porsche 718 ", 500))
# print(controller.add_car_to_driver("Peter", "SportsCar"))
#
# print(controller.create_car("SportsCar", "Porsche 911", 580))
# print(controller.add_car_to_driver("Peter", "SportsCar"))
# print(controller.add_car_to_driver("Peter", "SportsCar"))
# print(controller.create_car("MuscleCar", "BMW ALPINA B7", 290))
# print(controller.create_car("MuscleCar", "Mercedes-Benz AMG GLA 45", 420))
# print(controller.create_driver("John"))
# print(controller.create_driver("Jack"))
# print(controller.create_driver("Kelly"))
# print(controller.add_car_to_driver("Kelly", "MuscleCar"))
# print(controller.add_car_to_driver("Jack", "MuscleCar"))
# print(controller.add_car_to_driver("John", "SportsCar"))
# print(controller.create_race("Christmas Top Racers"))
#
# print(controller.add_driver_to_race("Christmas Top Racers", "John"))
# print(controller.add_driver_to_race("Christmas Top Racers", "John"))
# print(controller.add_driver_to_race("Christmas Top Racers", "Jack"))
# print(controller.add_driver_to_race("Christmas Top Racers", "Kelly"))
# print(controller.add_driver_to_race("Christmas Top Racers", "Peter"))
# print(controller.start_race("Christmas Top Racers"))
# [print(d.name, d.number_of_wins) for d in controller.drivers]